version: "3.8"
services: 
  web:
    container_name: php-7.4.21-apache_container
    depends_on: 
      - mysql
    # image: php:7.4.21-apache
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: api_dev
    #   # MYSQL_USER: api-admin
    #   MYSQL_USER: api-admin-dev
    #   MYSQL_PASSWORD: password
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8080:80

  mysql:
    container_name: mysql-8.0.26_container
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    # command: ["mysql", "--user=root", "--password=root", "api_dev", "<", "/scripts/grant_user_priv.sql"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_dev
      # MYSQL_USER: api-admin
      MYSQL_USER: api-admin-dev
      MYSQL_PASSWORD: password
    # volumes:
      # - ./scripts/grant_user_priv.sql:/scripts/grant_user_priv.sql
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: phpmyadmin-5.1.1_container
    depends_on:
      - mysql
    image: phpmyadmin:5.1.1
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql-8.0.26_container
      PMA_PORT: 3306
